version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_GOOGLE_CLIENT_ID=your-google-client-id
      - REACT_APP_FACEBOOK_APP_ID=your-facebook-app-id
      - REACT_APP_TWITTER_CLIENT_ID=your-twitter-client-id
      - REACT_APP_GITHUB_CLIENT_ID=your-github-client-id

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - GOOGLE_CLIENT_ID=your-google-client-id
      - GOOGLE_CLIENT_SECRET=your-google-client-secret

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
